FROM python:3.13.3-alpine as base

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV ENV=development

RUN apk add --no-cache \
    sox \
    ffmpeg \
    sox-dev \
    && rm -rf /var/cache/apk/*

WORKDIR /app

COPY ./requirements /app/requirements

RUN pip install --no-cache-dir -r requirements/dev.txt

COPY . /app

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]